### ISSUE TITLE
NetCore GUI

### ISSUE THREAD

**Issue by Dremor** [diogotr7/OpenRGB.NET#1]
Hi,

I started designing a GUI for OpenRGB on my spare time, using [GtkSharp](https://github.com/GtkSharp/GtkSharp) and NetCore3 (for now, I'll migrate to NET 5.0 soon), mostly in order to learn to create GTK apps in C#. 

It is still in very early stage (testing GTK standard widget, looking at how to create custom ones, imagining and drawing the future GUI, etc.), but I think I'll use your work in order to connect to OpenRGB.

I'll try to help you.

**Comment by diogotr7** [comment]
Hey, that's a cool idea. If it was me I'd use avalonia instead but that doesn't matter too much :p

Feel free to ask me anything about the client or make suggestions. I'm in the open rgb discord with the same username as here.

**Comment by Dremor** [comment]
Where can I find the Discord invite link ?
