### ISSUE TITLE
Is there any unique device ID?

### ISSUE THREAD

**Issue by Kaitoukid93** [diogotr7/OpenRGB.NET#19]
Hello! I have been using OpenRGB and it's great
I ran into a small problem:
My app converted OpenRGB detected device to my own device.
Everytime OpenRGb update the device list, my app will pull all controllers data and convert all available devices to my devices.
The problem is I cant compair existed device with new one to skip them if they are actually the same device
Using The Serial value is conflict if 2 devices have no Serial ( my logitech g903 wireless)
The device in openRGB list is not fixed by order, they are rearranged after rescan if there is new device added, so I can't just add the last devices to my list.
Sorry for my bad English

**Comment by diogotr7** [comment]
Hi,

No, there is no unique device Id. You might be able to combine name + vendor + path to get some kind of Id if you want but it's not a feature either OpenRGB or OpenRGB.NET has.
