### ISSUE TITLE
Explicit default constructor for Color

### ISSUE THREAD

**Issue by wfowler1** [diogotr7/OpenRGB.NET#22]
Currently the Color class includes the constructor
`public Color(byte red = 0, byte green = 0, byte blue = 0)`
This works fine for writing code, but I recently ran into a case where I needed to use Activator.CreateInstance to construct a new object which might be a Color. Since this constructor isn't parameterless, it's not seen as a default constructor. I can't use one of the overloads of CreateInstance that allows me to pass parameters because I don't know at compile-time whether it's a Color or not.

I propose adding a new single-line constructor to the Color class that's simply this:
`public Color() { }`

**Comment by diogotr7** [comment]
Added.
