### ISSUE TITLE
3.0 Protocol version gets ignored

### ISSUE THREAD

**Issue by qiangqiang101** [diogotr7/OpenRGB.NET#31]
![image](https://github.com/diogotr7/OpenRGB.NET/assets/11488961/0a5ab808-932b-4600-97b3-4f2d5594949f)
![image](https://github.com/diogotr7/OpenRGB.NET/assets/11488961/6f242176-2d3f-4dba-a048-6a4f3aa35657)

the latest working one is 2.2
this is same code but using 2.2
![image](https://github.com/diogotr7/OpenRGB.NET/assets/11488961/dad6a7c2-3544-4227-8a5c-29d6aefa323e)

**Comment by diogotr7** [comment]
Fixed with https://github.com/diogotr7/OpenRGB.NET/commit/0793deb971cece1f5a9b98a83680394b1fbe4e34
