### ISSUE TITLE
Support for updating device mode

### ISSUE THREAD

**Issue by cobrafast** [diogotr7/OpenRGB.NET#6]
Would be nice to be able to switch between the predefined modes in `Device.Modes`, e.g. update `Device.ActiveModeIndex`.

Or alternatively something like `OpenRGBClient.UpdateMode(int deviceId, int modeId)`.

OpenRGB-PyClient seems to be able to do it, but I have no idea how to port the code: https://github.com/bahorn/OpenRGB-PyClient/blob/master/openrgb/OpenRGB.py#L94

I would highly appreciate it if this could be implemented.

**Comment by diogotr7** [comment]
I added the function and tested it briefly on my G810. would be helpful if you could test it as well.

**Comment by cobrafast** [comment]
Yup, works for my Asus Aura controllers as well. Thank you very much!

**Comment by diogotr7** [comment]
Just pushed another commit that should let you set speed, direction, and colors on this set mode method. If you could test it it would help. Seems to work fine on my g810 with breathing and static modes.
