### ISSUE TITLE
new version support profile management

### ISSUE THREAD

**Issue by wojciech-Kokot** [diogotr7/OpenRGB.NET#9]
Is it possible to update OpenRGB.NET client due to new features in OPENRGB added? In pipeline  #252312272  profile management are supported.
new commands are :
NetworkClient::SendRequest_LoadProfile(std::string profile_name)
void NetworkClient::SendRequest_SaveProfile(std::string profile_name)
NetworkClient::SendRequest_GetProfileList()
and more 
I'm your big Fan and waiting forn new version

**Comment by sparten11740** [comment]
@diogotr7 could you publish the latest version with the profile management features to nuget? that'd be really appreciated, thank you!

**Comment by diogotr7** [comment]
I've submitted v1.6.0 to nuget just now. It should be indexed and become avilable soon.

**Comment by wojciech-Kokot** [comment]
thank You :)
